#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 142
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 3

enum ts_symbol_identifiers {
  anon_sym_let = 1,
  anon_sym_mut = 2,
  anon_sym_fn = 3,
  anon_sym_LPAREN = 4,
  anon_sym_COMMA = 5,
  anon_sym_RPAREN = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  anon_sym_while = 9,
  sym_multiply = 10,
  sym_divide = 11,
  sym_plus = 12,
  sym_minus = 13,
  sym_greater_than = 14,
  sym_greater_than_or_equal = 15,
  sym_less_than = 16,
  sym_less_than_or_equal = 17,
  sym_and = 18,
  sym_or = 19,
  sym_increment = 20,
  sym_decrement = 21,
  anon_sym_Str = 22,
  anon_sym_Num = 23,
  anon_sym_Bool = 24,
  sym_identifier = 25,
  anon_sym_DQUOTE = 26,
  aux_sym_string_token1 = 27,
  sym_number = 28,
  anon_sym_true = 29,
  anon_sym_false = 30,
  anon_sym_COLON = 31,
  anon_sym_EQ = 32,
  sym_source_file = 33,
  sym_statement = 34,
  sym_variable_definition = 35,
  sym__type_declaration = 36,
  sym_variable_binding = 37,
  sym_function_definition = 38,
  sym_parameters = 39,
  sym_param_def = 40,
  sym_return_type = 41,
  sym_block = 42,
  sym_while_loop = 43,
  sym_reassignment = 44,
  sym_compound_assignment = 45,
  sym__expression = 46,
  sym_binary_expression = 47,
  sym_primitive_type = 48,
  sym_primitive_value = 49,
  sym_string = 50,
  sym_boolean = 51,
  sym__colon = 52,
  sym__assign = 53,
  aux_sym_source_file_repeat1 = 54,
  aux_sym_parameters_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_let] = "let",
  [anon_sym_mut] = "mut",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_while] = "while",
  [sym_multiply] = "multiply",
  [sym_divide] = "divide",
  [sym_plus] = "plus",
  [sym_minus] = "minus",
  [sym_greater_than] = "greater_than",
  [sym_greater_than_or_equal] = "greater_than_or_equal",
  [sym_less_than] = "less_than",
  [sym_less_than_or_equal] = "less_than_or_equal",
  [sym_and] = "and",
  [sym_or] = "or",
  [sym_increment] = "increment",
  [sym_decrement] = "decrement",
  [anon_sym_Str] = "Str",
  [anon_sym_Num] = "Num",
  [anon_sym_Bool] = "Bool",
  [sym_identifier] = "identifier",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [sym_source_file] = "source_file",
  [sym_statement] = "statement",
  [sym_variable_definition] = "variable_definition",
  [sym__type_declaration] = "_type_declaration",
  [sym_variable_binding] = "variable_binding",
  [sym_function_definition] = "function_definition",
  [sym_parameters] = "parameters",
  [sym_param_def] = "param_def",
  [sym_return_type] = "return_type",
  [sym_block] = "block",
  [sym_while_loop] = "while_loop",
  [sym_reassignment] = "reassignment",
  [sym_compound_assignment] = "compound_assignment",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_primitive_type] = "primitive_type",
  [sym_primitive_value] = "primitive_value",
  [sym_string] = "string",
  [sym_boolean] = "boolean",
  [sym__colon] = "_colon",
  [sym__assign] = "_assign",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_mut] = anon_sym_mut,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_while] = anon_sym_while,
  [sym_multiply] = sym_multiply,
  [sym_divide] = sym_divide,
  [sym_plus] = sym_plus,
  [sym_minus] = sym_minus,
  [sym_greater_than] = sym_greater_than,
  [sym_greater_than_or_equal] = sym_greater_than_or_equal,
  [sym_less_than] = sym_less_than,
  [sym_less_than_or_equal] = sym_less_than_or_equal,
  [sym_and] = sym_and,
  [sym_or] = sym_or,
  [sym_increment] = sym_increment,
  [sym_decrement] = sym_decrement,
  [anon_sym_Str] = anon_sym_Str,
  [anon_sym_Num] = anon_sym_Num,
  [anon_sym_Bool] = anon_sym_Bool,
  [sym_identifier] = sym_identifier,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_source_file] = sym_source_file,
  [sym_statement] = sym_statement,
  [sym_variable_definition] = sym_variable_definition,
  [sym__type_declaration] = sym__type_declaration,
  [sym_variable_binding] = sym_variable_binding,
  [sym_function_definition] = sym_function_definition,
  [sym_parameters] = sym_parameters,
  [sym_param_def] = sym_param_def,
  [sym_return_type] = sym_return_type,
  [sym_block] = sym_block,
  [sym_while_loop] = sym_while_loop,
  [sym_reassignment] = sym_reassignment,
  [sym_compound_assignment] = sym_compound_assignment,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_primitive_type] = sym_primitive_type,
  [sym_primitive_value] = sym_primitive_value,
  [sym_string] = sym_string,
  [sym_boolean] = sym_boolean,
  [sym__colon] = sym__colon,
  [sym__assign] = sym__assign,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mut] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [sym_multiply] = {
    .visible = true,
    .named = true,
  },
  [sym_divide] = {
    .visible = true,
    .named = true,
  },
  [sym_plus] = {
    .visible = true,
    .named = true,
  },
  [sym_minus] = {
    .visible = true,
    .named = true,
  },
  [sym_greater_than] = {
    .visible = true,
    .named = true,
  },
  [sym_greater_than_or_equal] = {
    .visible = true,
    .named = true,
  },
  [sym_less_than] = {
    .visible = true,
    .named = true,
  },
  [sym_less_than_or_equal] = {
    .visible = true,
    .named = true,
  },
  [sym_and] = {
    .visible = true,
    .named = true,
  },
  [sym_or] = {
    .visible = true,
    .named = true,
  },
  [sym_increment] = {
    .visible = true,
    .named = true,
  },
  [sym_decrement] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Num] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Bool] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__type_declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_param_def] = {
    .visible = true,
    .named = true,
  },
  [sym_return_type] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_while_loop] = {
    .visible = true,
    .named = true,
  },
  [sym_reassignment] = {
    .visible = true,
    .named = true,
  },
  [sym_compound_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_value] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym__colon] = {
    .visible = false,
    .named = true,
  },
  [sym__assign] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_condition = 1,
  field_left = 2,
  field_operator = 3,
  field_right = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_condition] = "condition",
  [field_left] = "left",
  [field_operator] = "operator",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_condition, 1},
  [1] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 2,
  [9] = 9,
  [10] = 6,
  [11] = 5,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 7,
  [18] = 3,
  [19] = 12,
  [20] = 13,
  [21] = 14,
  [22] = 15,
  [23] = 16,
  [24] = 4,
  [25] = 9,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 26,
  [31] = 27,
  [32] = 28,
  [33] = 33,
  [34] = 33,
  [35] = 4,
  [36] = 7,
  [37] = 3,
  [38] = 12,
  [39] = 13,
  [40] = 14,
  [41] = 15,
  [42] = 16,
  [43] = 2,
  [44] = 9,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 51,
  [53] = 53,
  [54] = 54,
  [55] = 54,
  [56] = 56,
  [57] = 46,
  [58] = 47,
  [59] = 48,
  [60] = 49,
  [61] = 50,
  [62] = 51,
  [63] = 56,
  [64] = 46,
  [65] = 47,
  [66] = 48,
  [67] = 49,
  [68] = 50,
  [69] = 56,
  [70] = 53,
  [71] = 45,
  [72] = 72,
  [73] = 73,
  [74] = 72,
  [75] = 75,
  [76] = 75,
  [77] = 73,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 4,
  [82] = 82,
  [83] = 78,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 80,
  [88] = 88,
  [89] = 2,
  [90] = 9,
  [91] = 4,
  [92] = 2,
  [93] = 9,
  [94] = 88,
  [95] = 85,
  [96] = 86,
  [97] = 79,
  [98] = 84,
  [99] = 82,
  [100] = 100,
  [101] = 100,
  [102] = 102,
  [103] = 103,
  [104] = 103,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 116,
  [121] = 121,
  [122] = 115,
  [123] = 121,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 126,
  [131] = 131,
  [132] = 126,
  [133] = 126,
  [134] = 126,
  [135] = 135,
  [136] = 128,
  [137] = 128,
  [138] = 128,
  [139] = 128,
  [140] = 125,
  [141] = 124,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '"', 82,
        '(', 28,
        ')', 30,
        '*', 34,
        '+', 36,
        ',', 29,
        '-', 37,
        '/', 35,
        ':', 91,
        '<', 40,
        '=', 92,
        '>', 38,
        'B', 69,
        'N', 78,
        'S', 77,
        'a', 67,
        'f', 54,
        'l', 60,
        'm', 80,
        'o', 71,
        't', 73,
        'w', 61,
        '{', 31,
        '}', 32,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 82,
        '*', 34,
        '+', 36,
        '-', 37,
        '/', 35,
        '<', 40,
        '>', 38,
        'B', 12,
        'N', 19,
        'S', 18,
        'a', 11,
        'f', 4,
        'o', 14,
        't', 16,
        '{', 31,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(82);
      if (lookahead == 'f') ADVANCE(55);
      if (lookahead == 't') ADVANCE(73);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'd') ADVANCE(42);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(89);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(52);
      END_STATE();
    case 10:
      if (lookahead == 'm') ADVANCE(50);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(48);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 19:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      END_STATE();
    case 22:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '*', 34,
        '+', 36,
        '-', 37,
        '/', 35,
        '<', 40,
        '>', 38,
        'a', 67,
        'f', 68,
        'l', 60,
        'm', 80,
        'o', 71,
        'w', 61,
        '}', 32,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 23:
      if (eof) ADVANCE(24);
      if (lookahead == 'f') ADVANCE(68);
      if (lookahead == 'l') ADVANCE(60);
      if (lookahead == 'm') ADVANCE(80);
      if (lookahead == 'w') ADVANCE(61);
      if (lookahead == '}') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_mut);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_while);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_multiply);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_divide);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_plus);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_minus);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_greater_than);
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_greater_than_or_equal);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_less_than);
      if (lookahead == '=') ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_less_than_or_equal);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_and);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_and);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_or);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_or);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_increment);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_decrement);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_Str);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_Str);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_Num);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_Num);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_Bool);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_Bool);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(63);
      if (lookahead == 'n') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(84);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '+') ADVANCE(46);
      if (lookahead == '-') ADVANCE(47);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 23},
  [2] = {.lex_state = 22},
  [3] = {.lex_state = 22},
  [4] = {.lex_state = 22},
  [5] = {.lex_state = 22},
  [6] = {.lex_state = 22},
  [7] = {.lex_state = 22},
  [8] = {.lex_state = 22},
  [9] = {.lex_state = 22},
  [10] = {.lex_state = 22},
  [11] = {.lex_state = 22},
  [12] = {.lex_state = 22},
  [13] = {.lex_state = 22},
  [14] = {.lex_state = 22},
  [15] = {.lex_state = 22},
  [16] = {.lex_state = 22},
  [17] = {.lex_state = 22},
  [18] = {.lex_state = 22},
  [19] = {.lex_state = 22},
  [20] = {.lex_state = 22},
  [21] = {.lex_state = 22},
  [22] = {.lex_state = 22},
  [23] = {.lex_state = 22},
  [24] = {.lex_state = 22},
  [25] = {.lex_state = 22},
  [26] = {.lex_state = 23},
  [27] = {.lex_state = 23},
  [28] = {.lex_state = 23},
  [29] = {.lex_state = 23},
  [30] = {.lex_state = 23},
  [31] = {.lex_state = 23},
  [32] = {.lex_state = 23},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 23},
  [79] = {.lex_state = 23},
  [80] = {.lex_state = 23},
  [81] = {.lex_state = 23},
  [82] = {.lex_state = 23},
  [83] = {.lex_state = 23},
  [84] = {.lex_state = 23},
  [85] = {.lex_state = 23},
  [86] = {.lex_state = 23},
  [87] = {.lex_state = 23},
  [88] = {.lex_state = 23},
  [89] = {.lex_state = 23},
  [90] = {.lex_state = 23},
  [91] = {.lex_state = 23},
  [92] = {.lex_state = 23},
  [93] = {.lex_state = 23},
  [94] = {.lex_state = 23},
  [95] = {.lex_state = 23},
  [96] = {.lex_state = 23},
  [97] = {.lex_state = 23},
  [98] = {.lex_state = 23},
  [99] = {.lex_state = 23},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 1},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 1},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 1},
  [108] = {.lex_state = 1},
  [109] = {.lex_state = 1},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 3},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 3},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 3},
  [125] = {.lex_state = 3},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 3},
  [128] = {.lex_state = 83},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 83},
  [137] = {.lex_state = 83},
  [138] = {.lex_state = 83},
  [139] = {.lex_state = 83},
  [140] = {.lex_state = 3},
  [141] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_mut] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [sym_multiply] = ACTIONS(1),
    [sym_divide] = ACTIONS(1),
    [sym_plus] = ACTIONS(1),
    [sym_minus] = ACTIONS(1),
    [sym_greater_than] = ACTIONS(1),
    [sym_greater_than_or_equal] = ACTIONS(1),
    [sym_less_than] = ACTIONS(1),
    [sym_less_than_or_equal] = ACTIONS(1),
    [sym_and] = ACTIONS(1),
    [sym_or] = ACTIONS(1),
    [sym_increment] = ACTIONS(1),
    [sym_decrement] = ACTIONS(1),
    [anon_sym_Str] = ACTIONS(1),
    [anon_sym_Num] = ACTIONS(1),
    [anon_sym_Bool] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(131),
    [sym_statement] = STATE(29),
    [sym_variable_definition] = STATE(78),
    [sym_variable_binding] = STATE(124),
    [sym_function_definition] = STATE(78),
    [sym_while_loop] = STATE(78),
    [sym_reassignment] = STATE(78),
    [sym_compound_assignment] = STATE(78),
    [aux_sym_source_file_repeat1] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_mut] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [anon_sym_while] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(15), 7,
      anon_sym_RBRACE,
      sym_multiply,
      sym_divide,
      sym_plus,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(13), 9,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_greater_than,
      sym_less_than,
      sym_and,
      sym_or,
      sym_identifier,
  [21] = 3,
    ACTIONS(21), 1,
      sym_multiply,
    ACTIONS(17), 6,
      ts_builtin_sym_end,
      sym_divide,
      sym_plus,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(19), 9,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_greater_than,
      sym_less_than,
      sym_and,
      sym_or,
      sym_identifier,
  [44] = 2,
    ACTIONS(23), 7,
      ts_builtin_sym_end,
      sym_multiply,
      sym_divide,
      sym_plus,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(25), 9,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_greater_than,
      sym_less_than,
      sym_and,
      sym_or,
      sym_identifier,
  [65] = 10,
    ACTIONS(21), 1,
      sym_multiply,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      sym_divide,
    ACTIONS(33), 1,
      sym_plus,
    ACTIONS(35), 1,
      sym_minus,
    ACTIONS(41), 1,
      sym_and,
    ACTIONS(43), 1,
      sym_or,
    ACTIONS(37), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(39), 2,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(29), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [102] = 10,
    ACTIONS(21), 1,
      sym_multiply,
    ACTIONS(31), 1,
      sym_divide,
    ACTIONS(33), 1,
      sym_plus,
    ACTIONS(35), 1,
      sym_minus,
    ACTIONS(41), 1,
      sym_and,
    ACTIONS(43), 1,
      sym_or,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(39), 2,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(47), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [139] = 2,
    ACTIONS(17), 7,
      ts_builtin_sym_end,
      sym_multiply,
      sym_divide,
      sym_plus,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(19), 9,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_greater_than,
      sym_less_than,
      sym_and,
      sym_or,
      sym_identifier,
  [160] = 2,
    ACTIONS(15), 7,
      ts_builtin_sym_end,
      sym_multiply,
      sym_divide,
      sym_plus,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(13), 9,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_greater_than,
      sym_less_than,
      sym_and,
      sym_or,
      sym_identifier,
  [181] = 2,
    ACTIONS(49), 7,
      ts_builtin_sym_end,
      sym_multiply,
      sym_divide,
      sym_plus,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(51), 9,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_greater_than,
      sym_less_than,
      sym_and,
      sym_or,
      sym_identifier,
  [202] = 10,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    ACTIONS(53), 1,
      sym_multiply,
    ACTIONS(55), 1,
      sym_divide,
    ACTIONS(57), 1,
      sym_plus,
    ACTIONS(59), 1,
      sym_minus,
    ACTIONS(65), 1,
      sym_and,
    ACTIONS(67), 1,
      sym_or,
    ACTIONS(61), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(63), 2,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(47), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [239] = 10,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    ACTIONS(53), 1,
      sym_multiply,
    ACTIONS(55), 1,
      sym_divide,
    ACTIONS(57), 1,
      sym_plus,
    ACTIONS(59), 1,
      sym_minus,
    ACTIONS(65), 1,
      sym_and,
    ACTIONS(67), 1,
      sym_or,
    ACTIONS(61), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(63), 2,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(29), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [276] = 4,
    ACTIONS(21), 1,
      sym_multiply,
    ACTIONS(31), 1,
      sym_divide,
    ACTIONS(17), 5,
      ts_builtin_sym_end,
      sym_plus,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(19), 9,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_greater_than,
      sym_less_than,
      sym_and,
      sym_or,
      sym_identifier,
  [301] = 5,
    ACTIONS(21), 1,
      sym_multiply,
    ACTIONS(31), 1,
      sym_divide,
    ACTIONS(33), 1,
      sym_plus,
    ACTIONS(17), 4,
      ts_builtin_sym_end,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(19), 9,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_greater_than,
      sym_less_than,
      sym_and,
      sym_or,
      sym_identifier,
  [328] = 6,
    ACTIONS(21), 1,
      sym_multiply,
    ACTIONS(31), 1,
      sym_divide,
    ACTIONS(33), 1,
      sym_plus,
    ACTIONS(35), 1,
      sym_minus,
    ACTIONS(17), 3,
      ts_builtin_sym_end,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(19), 9,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_greater_than,
      sym_less_than,
      sym_and,
      sym_or,
      sym_identifier,
  [357] = 8,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      sym_multiply,
    ACTIONS(31), 1,
      sym_divide,
    ACTIONS(33), 1,
      sym_plus,
    ACTIONS(35), 1,
      sym_minus,
    ACTIONS(37), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(39), 2,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(19), 7,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_and,
      sym_or,
      sym_identifier,
  [390] = 9,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      sym_multiply,
    ACTIONS(31), 1,
      sym_divide,
    ACTIONS(33), 1,
      sym_plus,
    ACTIONS(35), 1,
      sym_minus,
    ACTIONS(41), 1,
      sym_and,
    ACTIONS(37), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(39), 2,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(19), 6,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_or,
      sym_identifier,
  [425] = 2,
    ACTIONS(17), 7,
      anon_sym_RBRACE,
      sym_multiply,
      sym_divide,
      sym_plus,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(19), 9,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_greater_than,
      sym_less_than,
      sym_and,
      sym_or,
      sym_identifier,
  [446] = 3,
    ACTIONS(53), 1,
      sym_multiply,
    ACTIONS(17), 6,
      anon_sym_RBRACE,
      sym_divide,
      sym_plus,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(19), 9,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_greater_than,
      sym_less_than,
      sym_and,
      sym_or,
      sym_identifier,
  [469] = 4,
    ACTIONS(53), 1,
      sym_multiply,
    ACTIONS(55), 1,
      sym_divide,
    ACTIONS(17), 5,
      anon_sym_RBRACE,
      sym_plus,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(19), 9,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_greater_than,
      sym_less_than,
      sym_and,
      sym_or,
      sym_identifier,
  [494] = 5,
    ACTIONS(53), 1,
      sym_multiply,
    ACTIONS(55), 1,
      sym_divide,
    ACTIONS(57), 1,
      sym_plus,
    ACTIONS(17), 4,
      anon_sym_RBRACE,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(19), 9,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_greater_than,
      sym_less_than,
      sym_and,
      sym_or,
      sym_identifier,
  [521] = 6,
    ACTIONS(53), 1,
      sym_multiply,
    ACTIONS(55), 1,
      sym_divide,
    ACTIONS(57), 1,
      sym_plus,
    ACTIONS(59), 1,
      sym_minus,
    ACTIONS(17), 3,
      anon_sym_RBRACE,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(19), 9,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_greater_than,
      sym_less_than,
      sym_and,
      sym_or,
      sym_identifier,
  [550] = 8,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(53), 1,
      sym_multiply,
    ACTIONS(55), 1,
      sym_divide,
    ACTIONS(57), 1,
      sym_plus,
    ACTIONS(59), 1,
      sym_minus,
    ACTIONS(61), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(63), 2,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(19), 7,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_and,
      sym_or,
      sym_identifier,
  [583] = 9,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(53), 1,
      sym_multiply,
    ACTIONS(55), 1,
      sym_divide,
    ACTIONS(57), 1,
      sym_plus,
    ACTIONS(59), 1,
      sym_minus,
    ACTIONS(65), 1,
      sym_and,
    ACTIONS(61), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(63), 2,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(19), 6,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_or,
      sym_identifier,
  [618] = 2,
    ACTIONS(23), 7,
      anon_sym_RBRACE,
      sym_multiply,
      sym_divide,
      sym_plus,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(25), 9,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_greater_than,
      sym_less_than,
      sym_and,
      sym_or,
      sym_identifier,
  [639] = 2,
    ACTIONS(49), 7,
      anon_sym_RBRACE,
      sym_multiply,
      sym_divide,
      sym_plus,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(51), 9,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_greater_than,
      sym_less_than,
      sym_and,
      sym_or,
      sym_identifier,
  [660] = 8,
    ACTIONS(72), 1,
      anon_sym_fn,
    ACTIONS(75), 1,
      anon_sym_RBRACE,
    ACTIONS(77), 1,
      anon_sym_while,
    ACTIONS(80), 1,
      sym_identifier,
    STATE(141), 1,
      sym_variable_binding,
    ACTIONS(69), 2,
      anon_sym_let,
      anon_sym_mut,
    STATE(26), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(83), 5,
      sym_variable_definition,
      sym_function_definition,
      sym_while_loop,
      sym_reassignment,
      sym_compound_assignment,
  [691] = 8,
    ACTIONS(83), 1,
      anon_sym_fn,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
    ACTIONS(87), 1,
      anon_sym_while,
    ACTIONS(89), 1,
      sym_identifier,
    STATE(141), 1,
      sym_variable_binding,
    ACTIONS(5), 2,
      anon_sym_let,
      anon_sym_mut,
    STATE(28), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(83), 5,
      sym_variable_definition,
      sym_function_definition,
      sym_while_loop,
      sym_reassignment,
      sym_compound_assignment,
  [722] = 8,
    ACTIONS(83), 1,
      anon_sym_fn,
    ACTIONS(87), 1,
      anon_sym_while,
    ACTIONS(89), 1,
      sym_identifier,
    ACTIONS(91), 1,
      anon_sym_RBRACE,
    STATE(141), 1,
      sym_variable_binding,
    ACTIONS(5), 2,
      anon_sym_let,
      anon_sym_mut,
    STATE(26), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(83), 5,
      sym_variable_definition,
      sym_function_definition,
      sym_while_loop,
      sym_reassignment,
      sym_compound_assignment,
  [753] = 8,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_while,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    STATE(124), 1,
      sym_variable_binding,
    ACTIONS(5), 2,
      anon_sym_let,
      anon_sym_mut,
    STATE(30), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(78), 5,
      sym_variable_definition,
      sym_function_definition,
      sym_while_loop,
      sym_reassignment,
      sym_compound_assignment,
  [784] = 8,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    ACTIONS(95), 1,
      anon_sym_fn,
    ACTIONS(98), 1,
      anon_sym_while,
    ACTIONS(101), 1,
      sym_identifier,
    STATE(124), 1,
      sym_variable_binding,
    ACTIONS(69), 2,
      anon_sym_let,
      anon_sym_mut,
    STATE(30), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(78), 5,
      sym_variable_definition,
      sym_function_definition,
      sym_while_loop,
      sym_reassignment,
      sym_compound_assignment,
  [815] = 8,
    ACTIONS(83), 1,
      anon_sym_fn,
    ACTIONS(87), 1,
      anon_sym_while,
    ACTIONS(89), 1,
      sym_identifier,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    STATE(141), 1,
      sym_variable_binding,
    ACTIONS(5), 2,
      anon_sym_let,
      anon_sym_mut,
    STATE(32), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(83), 5,
      sym_variable_definition,
      sym_function_definition,
      sym_while_loop,
      sym_reassignment,
      sym_compound_assignment,
  [846] = 8,
    ACTIONS(83), 1,
      anon_sym_fn,
    ACTIONS(87), 1,
      anon_sym_while,
    ACTIONS(89), 1,
      sym_identifier,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(141), 1,
      sym_variable_binding,
    ACTIONS(5), 2,
      anon_sym_let,
      anon_sym_mut,
    STATE(26), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(83), 5,
      sym_variable_definition,
      sym_function_definition,
      sym_while_loop,
      sym_reassignment,
      sym_compound_assignment,
  [877] = 10,
    ACTIONS(108), 1,
      anon_sym_LBRACE,
    ACTIONS(110), 1,
      sym_multiply,
    ACTIONS(112), 1,
      sym_divide,
    ACTIONS(114), 1,
      sym_plus,
    ACTIONS(116), 1,
      sym_minus,
    ACTIONS(122), 1,
      sym_and,
    ACTIONS(124), 1,
      sym_or,
    STATE(88), 1,
      sym_block,
    ACTIONS(118), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(120), 2,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
  [910] = 10,
    ACTIONS(110), 1,
      sym_multiply,
    ACTIONS(112), 1,
      sym_divide,
    ACTIONS(114), 1,
      sym_plus,
    ACTIONS(116), 1,
      sym_minus,
    ACTIONS(122), 1,
      sym_and,
    ACTIONS(124), 1,
      sym_or,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    STATE(94), 1,
      sym_block,
    ACTIONS(118), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(120), 2,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
  [943] = 2,
    ACTIONS(25), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(23), 9,
      anon_sym_LBRACE,
      sym_multiply,
      sym_divide,
      sym_plus,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
      sym_and,
      sym_or,
  [959] = 2,
    ACTIONS(19), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(17), 9,
      anon_sym_LBRACE,
      sym_multiply,
      sym_divide,
      sym_plus,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
      sym_and,
      sym_or,
  [975] = 3,
    ACTIONS(110), 1,
      sym_multiply,
    ACTIONS(19), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(17), 8,
      anon_sym_LBRACE,
      sym_divide,
      sym_plus,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
      sym_and,
      sym_or,
  [993] = 4,
    ACTIONS(110), 1,
      sym_multiply,
    ACTIONS(112), 1,
      sym_divide,
    ACTIONS(19), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(17), 7,
      anon_sym_LBRACE,
      sym_plus,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
      sym_and,
      sym_or,
  [1013] = 5,
    ACTIONS(110), 1,
      sym_multiply,
    ACTIONS(112), 1,
      sym_divide,
    ACTIONS(114), 1,
      sym_plus,
    ACTIONS(19), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(17), 6,
      anon_sym_LBRACE,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
      sym_and,
      sym_or,
  [1035] = 6,
    ACTIONS(110), 1,
      sym_multiply,
    ACTIONS(112), 1,
      sym_divide,
    ACTIONS(114), 1,
      sym_plus,
    ACTIONS(116), 1,
      sym_minus,
    ACTIONS(19), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(17), 5,
      anon_sym_LBRACE,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
      sym_and,
      sym_or,
  [1059] = 7,
    ACTIONS(110), 1,
      sym_multiply,
    ACTIONS(112), 1,
      sym_divide,
    ACTIONS(114), 1,
      sym_plus,
    ACTIONS(116), 1,
      sym_minus,
    ACTIONS(118), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(120), 2,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
    ACTIONS(17), 3,
      anon_sym_LBRACE,
      sym_and,
      sym_or,
  [1085] = 8,
    ACTIONS(110), 1,
      sym_multiply,
    ACTIONS(112), 1,
      sym_divide,
    ACTIONS(114), 1,
      sym_plus,
    ACTIONS(116), 1,
      sym_minus,
    ACTIONS(122), 1,
      sym_and,
    ACTIONS(17), 2,
      anon_sym_LBRACE,
      sym_or,
    ACTIONS(118), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(120), 2,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
  [1113] = 2,
    ACTIONS(13), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(15), 9,
      anon_sym_LBRACE,
      sym_multiply,
      sym_divide,
      sym_plus,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
      sym_and,
      sym_or,
  [1129] = 2,
    ACTIONS(51), 2,
      sym_greater_than,
      sym_less_than,
    ACTIONS(49), 9,
      anon_sym_LBRACE,
      sym_multiply,
      sym_divide,
      sym_plus,
      sym_minus,
      sym_greater_than_or_equal,
      sym_less_than_or_equal,
      sym_and,
      sym_or,
  [1145] = 6,
    ACTIONS(128), 1,
      sym_identifier,
    ACTIONS(130), 1,
      anon_sym_DQUOTE,
    ACTIONS(132), 1,
      sym_number,
    ACTIONS(134), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(8), 2,
      sym_string,
      sym_boolean,
    STATE(6), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1168] = 6,
    ACTIONS(130), 1,
      anon_sym_DQUOTE,
    ACTIONS(132), 1,
      sym_number,
    ACTIONS(136), 1,
      sym_identifier,
    ACTIONS(134), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(8), 2,
      sym_string,
      sym_boolean,
    STATE(12), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1191] = 6,
    ACTIONS(130), 1,
      anon_sym_DQUOTE,
    ACTIONS(132), 1,
      sym_number,
    ACTIONS(138), 1,
      sym_identifier,
    ACTIONS(134), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(8), 2,
      sym_string,
      sym_boolean,
    STATE(13), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1214] = 6,
    ACTIONS(130), 1,
      anon_sym_DQUOTE,
    ACTIONS(132), 1,
      sym_number,
    ACTIONS(140), 1,
      sym_identifier,
    ACTIONS(134), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(8), 2,
      sym_string,
      sym_boolean,
    STATE(14), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1237] = 6,
    ACTIONS(130), 1,
      anon_sym_DQUOTE,
    ACTIONS(132), 1,
      sym_number,
    ACTIONS(142), 1,
      sym_identifier,
    ACTIONS(134), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(8), 2,
      sym_string,
      sym_boolean,
    STATE(15), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1260] = 6,
    ACTIONS(130), 1,
      anon_sym_DQUOTE,
    ACTIONS(132), 1,
      sym_number,
    ACTIONS(144), 1,
      sym_identifier,
    ACTIONS(134), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(8), 2,
      sym_string,
      sym_boolean,
    STATE(16), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1283] = 6,
    ACTIONS(146), 1,
      sym_identifier,
    ACTIONS(148), 1,
      anon_sym_DQUOTE,
    ACTIONS(150), 1,
      sym_number,
    ACTIONS(152), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym_string,
      sym_boolean,
    STATE(17), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1306] = 6,
    ACTIONS(130), 1,
      anon_sym_DQUOTE,
    ACTIONS(132), 1,
      sym_number,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(134), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(8), 2,
      sym_string,
      sym_boolean,
    STATE(7), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1329] = 6,
    ACTIONS(130), 1,
      anon_sym_DQUOTE,
    ACTIONS(132), 1,
      sym_number,
    ACTIONS(156), 1,
      sym_identifier,
    ACTIONS(134), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(8), 2,
      sym_string,
      sym_boolean,
    STATE(5), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1352] = 6,
    ACTIONS(158), 1,
      sym_identifier,
    ACTIONS(160), 1,
      anon_sym_DQUOTE,
    ACTIONS(162), 1,
      sym_number,
    ACTIONS(164), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_string,
      sym_boolean,
    STATE(34), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1375] = 6,
    ACTIONS(160), 1,
      anon_sym_DQUOTE,
    ACTIONS(162), 1,
      sym_number,
    ACTIONS(166), 1,
      sym_identifier,
    ACTIONS(164), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_string,
      sym_boolean,
    STATE(33), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1398] = 6,
    ACTIONS(148), 1,
      anon_sym_DQUOTE,
    ACTIONS(150), 1,
      sym_number,
    ACTIONS(168), 1,
      sym_identifier,
    ACTIONS(152), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym_string,
      sym_boolean,
    STATE(18), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1421] = 6,
    ACTIONS(148), 1,
      anon_sym_DQUOTE,
    ACTIONS(150), 1,
      sym_number,
    ACTIONS(170), 1,
      sym_identifier,
    ACTIONS(152), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym_string,
      sym_boolean,
    STATE(19), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1444] = 6,
    ACTIONS(148), 1,
      anon_sym_DQUOTE,
    ACTIONS(150), 1,
      sym_number,
    ACTIONS(172), 1,
      sym_identifier,
    ACTIONS(152), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym_string,
      sym_boolean,
    STATE(20), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1467] = 6,
    ACTIONS(148), 1,
      anon_sym_DQUOTE,
    ACTIONS(150), 1,
      sym_number,
    ACTIONS(174), 1,
      sym_identifier,
    ACTIONS(152), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym_string,
      sym_boolean,
    STATE(21), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1490] = 6,
    ACTIONS(148), 1,
      anon_sym_DQUOTE,
    ACTIONS(150), 1,
      sym_number,
    ACTIONS(176), 1,
      sym_identifier,
    ACTIONS(152), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym_string,
      sym_boolean,
    STATE(22), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1513] = 6,
    ACTIONS(148), 1,
      anon_sym_DQUOTE,
    ACTIONS(150), 1,
      sym_number,
    ACTIONS(178), 1,
      sym_identifier,
    ACTIONS(152), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym_string,
      sym_boolean,
    STATE(23), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1536] = 6,
    ACTIONS(160), 1,
      anon_sym_DQUOTE,
    ACTIONS(162), 1,
      sym_number,
    ACTIONS(180), 1,
      sym_identifier,
    ACTIONS(164), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_string,
      sym_boolean,
    STATE(36), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1559] = 6,
    ACTIONS(160), 1,
      anon_sym_DQUOTE,
    ACTIONS(162), 1,
      sym_number,
    ACTIONS(182), 1,
      sym_identifier,
    ACTIONS(164), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_string,
      sym_boolean,
    STATE(37), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1582] = 6,
    ACTIONS(160), 1,
      anon_sym_DQUOTE,
    ACTIONS(162), 1,
      sym_number,
    ACTIONS(184), 1,
      sym_identifier,
    ACTIONS(164), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_string,
      sym_boolean,
    STATE(38), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1605] = 6,
    ACTIONS(160), 1,
      anon_sym_DQUOTE,
    ACTIONS(162), 1,
      sym_number,
    ACTIONS(186), 1,
      sym_identifier,
    ACTIONS(164), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_string,
      sym_boolean,
    STATE(39), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1628] = 6,
    ACTIONS(160), 1,
      anon_sym_DQUOTE,
    ACTIONS(162), 1,
      sym_number,
    ACTIONS(188), 1,
      sym_identifier,
    ACTIONS(164), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_string,
      sym_boolean,
    STATE(40), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1651] = 6,
    ACTIONS(160), 1,
      anon_sym_DQUOTE,
    ACTIONS(162), 1,
      sym_number,
    ACTIONS(190), 1,
      sym_identifier,
    ACTIONS(164), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_string,
      sym_boolean,
    STATE(41), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1674] = 6,
    ACTIONS(160), 1,
      anon_sym_DQUOTE,
    ACTIONS(162), 1,
      sym_number,
    ACTIONS(192), 1,
      sym_identifier,
    ACTIONS(164), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_string,
      sym_boolean,
    STATE(42), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1697] = 6,
    ACTIONS(130), 1,
      anon_sym_DQUOTE,
    ACTIONS(132), 1,
      sym_number,
    ACTIONS(194), 1,
      sym_identifier,
    ACTIONS(134), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(8), 2,
      sym_string,
      sym_boolean,
    STATE(3), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1720] = 6,
    ACTIONS(148), 1,
      anon_sym_DQUOTE,
    ACTIONS(150), 1,
      sym_number,
    ACTIONS(196), 1,
      sym_identifier,
    ACTIONS(152), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym_string,
      sym_boolean,
    STATE(11), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1743] = 6,
    ACTIONS(148), 1,
      anon_sym_DQUOTE,
    ACTIONS(150), 1,
      sym_number,
    ACTIONS(198), 1,
      sym_identifier,
    ACTIONS(152), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym_string,
      sym_boolean,
    STATE(10), 3,
      sym__expression,
      sym_binary_expression,
      sym_primitive_value,
  [1766] = 5,
    ACTIONS(108), 1,
      anon_sym_LBRACE,
    STATE(79), 1,
      sym_block,
    STATE(120), 1,
      sym_return_type,
    STATE(135), 1,
      sym_primitive_type,
    ACTIONS(200), 3,
      anon_sym_Str,
      anon_sym_Num,
      anon_sym_Bool,
  [1784] = 5,
    ACTIONS(202), 1,
      anon_sym_DQUOTE,
    ACTIONS(204), 1,
      sym_number,
    STATE(80), 1,
      sym_primitive_value,
    ACTIONS(206), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(92), 2,
      sym_string,
      sym_boolean,
  [1802] = 5,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    STATE(97), 1,
      sym_block,
    STATE(116), 1,
      sym_return_type,
    STATE(135), 1,
      sym_primitive_type,
    ACTIONS(200), 3,
      anon_sym_Str,
      anon_sym_Num,
      anon_sym_Bool,
  [1820] = 5,
    ACTIONS(202), 1,
      anon_sym_DQUOTE,
    ACTIONS(204), 1,
      sym_number,
    STATE(95), 1,
      sym_primitive_value,
    ACTIONS(206), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(92), 2,
      sym_string,
      sym_boolean,
  [1838] = 5,
    ACTIONS(208), 1,
      anon_sym_DQUOTE,
    ACTIONS(210), 1,
      sym_number,
    STATE(85), 1,
      sym_primitive_value,
    ACTIONS(212), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(89), 2,
      sym_string,
      sym_boolean,
  [1856] = 5,
    ACTIONS(208), 1,
      anon_sym_DQUOTE,
    ACTIONS(210), 1,
      sym_number,
    STATE(87), 1,
      sym_primitive_value,
    ACTIONS(212), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(89), 2,
      sym_string,
      sym_boolean,
  [1874] = 2,
    ACTIONS(214), 1,
      ts_builtin_sym_end,
    ACTIONS(216), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [1885] = 2,
    ACTIONS(218), 1,
      ts_builtin_sym_end,
    ACTIONS(220), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [1896] = 2,
    ACTIONS(222), 1,
      ts_builtin_sym_end,
    ACTIONS(224), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [1907] = 2,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [1918] = 2,
    ACTIONS(228), 1,
      anon_sym_RBRACE,
    ACTIONS(226), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [1929] = 2,
    ACTIONS(214), 1,
      anon_sym_RBRACE,
    ACTIONS(216), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [1940] = 2,
    ACTIONS(230), 1,
      ts_builtin_sym_end,
    ACTIONS(232), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [1951] = 2,
    ACTIONS(236), 1,
      anon_sym_RBRACE,
    ACTIONS(234), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [1962] = 2,
    ACTIONS(240), 1,
      anon_sym_RBRACE,
    ACTIONS(238), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [1973] = 2,
    ACTIONS(222), 1,
      anon_sym_RBRACE,
    ACTIONS(224), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [1984] = 2,
    ACTIONS(242), 1,
      ts_builtin_sym_end,
    ACTIONS(244), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [1995] = 2,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [2006] = 2,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(51), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [2017] = 2,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    ACTIONS(25), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [2028] = 2,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [2039] = 2,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [2050] = 2,
    ACTIONS(242), 1,
      anon_sym_RBRACE,
    ACTIONS(244), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [2061] = 2,
    ACTIONS(236), 1,
      ts_builtin_sym_end,
    ACTIONS(234), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [2072] = 2,
    ACTIONS(240), 1,
      ts_builtin_sym_end,
    ACTIONS(238), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [2083] = 2,
    ACTIONS(218), 1,
      anon_sym_RBRACE,
    ACTIONS(220), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [2094] = 2,
    ACTIONS(230), 1,
      anon_sym_RBRACE,
    ACTIONS(232), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [2105] = 2,
    ACTIONS(228), 1,
      ts_builtin_sym_end,
    ACTIONS(226), 5,
      anon_sym_let,
      anon_sym_mut,
      anon_sym_fn,
      anon_sym_while,
      sym_identifier,
  [2116] = 5,
    ACTIONS(246), 1,
      anon_sym_COLON,
    ACTIONS(248), 1,
      anon_sym_EQ,
    STATE(75), 1,
      sym__assign,
    STATE(102), 1,
      sym__colon,
    STATE(115), 1,
      sym__type_declaration,
  [2132] = 5,
    ACTIONS(246), 1,
      anon_sym_COLON,
    ACTIONS(250), 1,
      anon_sym_EQ,
    STATE(76), 1,
      sym__assign,
    STATE(102), 1,
      sym__colon,
    STATE(122), 1,
      sym__type_declaration,
  [2148] = 2,
    STATE(129), 1,
      sym_primitive_type,
    ACTIONS(200), 3,
      anon_sym_Str,
      anon_sym_Num,
      anon_sym_Bool,
  [2157] = 3,
    ACTIONS(254), 1,
      anon_sym_EQ,
    STATE(71), 1,
      sym__assign,
    ACTIONS(252), 2,
      sym_increment,
      sym_decrement,
  [2168] = 3,
    ACTIONS(258), 1,
      anon_sym_EQ,
    STATE(45), 1,
      sym__assign,
    ACTIONS(256), 2,
      sym_increment,
      sym_decrement,
  [2179] = 1,
    ACTIONS(260), 4,
      anon_sym_LBRACE,
      anon_sym_Str,
      anon_sym_Num,
      anon_sym_Bool,
  [2186] = 1,
    ACTIONS(262), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_EQ,
  [2193] = 1,
    ACTIONS(264), 4,
      anon_sym_LBRACE,
      anon_sym_Str,
      anon_sym_Num,
      anon_sym_Bool,
  [2200] = 2,
    STATE(117), 1,
      sym_primitive_type,
    ACTIONS(200), 3,
      anon_sym_Str,
      anon_sym_Num,
      anon_sym_Bool,
  [2209] = 1,
    ACTIONS(266), 4,
      anon_sym_LBRACE,
      anon_sym_Str,
      anon_sym_Num,
      anon_sym_Bool,
  [2216] = 3,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
    STATE(110), 1,
      aux_sym_parameters_repeat1,
  [2226] = 3,
    ACTIONS(273), 1,
      anon_sym_RPAREN,
    ACTIONS(275), 1,
      sym_identifier,
    STATE(112), 1,
      sym_param_def,
  [2236] = 3,
    ACTIONS(277), 1,
      anon_sym_COMMA,
    ACTIONS(279), 1,
      anon_sym_RPAREN,
    STATE(113), 1,
      aux_sym_parameters_repeat1,
  [2246] = 3,
    ACTIONS(277), 1,
      anon_sym_COMMA,
    ACTIONS(281), 1,
      anon_sym_RPAREN,
    STATE(110), 1,
      aux_sym_parameters_repeat1,
  [2256] = 2,
    ACTIONS(283), 1,
      anon_sym_COLON,
    STATE(108), 1,
      sym__colon,
  [2263] = 2,
    ACTIONS(285), 1,
      anon_sym_EQ,
    STATE(73), 1,
      sym__assign,
  [2270] = 2,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    STATE(86), 1,
      sym_block,
  [2277] = 1,
    ACTIONS(287), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2282] = 1,
    ACTIONS(271), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2287] = 2,
    ACTIONS(275), 1,
      sym_identifier,
    STATE(118), 1,
      sym_param_def,
  [2294] = 2,
    ACTIONS(108), 1,
      anon_sym_LBRACE,
    STATE(96), 1,
      sym_block,
  [2301] = 2,
    ACTIONS(289), 1,
      anon_sym_LPAREN,
    STATE(72), 1,
      sym_parameters,
  [2308] = 2,
    ACTIONS(291), 1,
      anon_sym_EQ,
    STATE(77), 1,
      sym__assign,
  [2315] = 2,
    ACTIONS(289), 1,
      anon_sym_LPAREN,
    STATE(74), 1,
      sym_parameters,
  [2322] = 1,
    ACTIONS(293), 1,
      sym_identifier,
  [2326] = 1,
    ACTIONS(295), 1,
      sym_identifier,
  [2330] = 1,
    ACTIONS(297), 1,
      anon_sym_DQUOTE,
  [2334] = 1,
    ACTIONS(299), 1,
      sym_identifier,
  [2338] = 1,
    ACTIONS(301), 1,
      aux_sym_string_token1,
  [2342] = 1,
    ACTIONS(303), 1,
      anon_sym_EQ,
  [2346] = 1,
    ACTIONS(305), 1,
      anon_sym_DQUOTE,
  [2350] = 1,
    ACTIONS(307), 1,
      ts_builtin_sym_end,
  [2354] = 1,
    ACTIONS(309), 1,
      anon_sym_DQUOTE,
  [2358] = 1,
    ACTIONS(311), 1,
      anon_sym_DQUOTE,
  [2362] = 1,
    ACTIONS(313), 1,
      anon_sym_DQUOTE,
  [2366] = 1,
    ACTIONS(315), 1,
      anon_sym_LBRACE,
  [2370] = 1,
    ACTIONS(317), 1,
      aux_sym_string_token1,
  [2374] = 1,
    ACTIONS(319), 1,
      aux_sym_string_token1,
  [2378] = 1,
    ACTIONS(321), 1,
      aux_sym_string_token1,
  [2382] = 1,
    ACTIONS(323), 1,
      aux_sym_string_token1,
  [2386] = 1,
    ACTIONS(325), 1,
      sym_identifier,
  [2390] = 1,
    ACTIONS(327), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 21,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 65,
  [SMALL_STATE(6)] = 102,
  [SMALL_STATE(7)] = 139,
  [SMALL_STATE(8)] = 160,
  [SMALL_STATE(9)] = 181,
  [SMALL_STATE(10)] = 202,
  [SMALL_STATE(11)] = 239,
  [SMALL_STATE(12)] = 276,
  [SMALL_STATE(13)] = 301,
  [SMALL_STATE(14)] = 328,
  [SMALL_STATE(15)] = 357,
  [SMALL_STATE(16)] = 390,
  [SMALL_STATE(17)] = 425,
  [SMALL_STATE(18)] = 446,
  [SMALL_STATE(19)] = 469,
  [SMALL_STATE(20)] = 494,
  [SMALL_STATE(21)] = 521,
  [SMALL_STATE(22)] = 550,
  [SMALL_STATE(23)] = 583,
  [SMALL_STATE(24)] = 618,
  [SMALL_STATE(25)] = 639,
  [SMALL_STATE(26)] = 660,
  [SMALL_STATE(27)] = 691,
  [SMALL_STATE(28)] = 722,
  [SMALL_STATE(29)] = 753,
  [SMALL_STATE(30)] = 784,
  [SMALL_STATE(31)] = 815,
  [SMALL_STATE(32)] = 846,
  [SMALL_STATE(33)] = 877,
  [SMALL_STATE(34)] = 910,
  [SMALL_STATE(35)] = 943,
  [SMALL_STATE(36)] = 959,
  [SMALL_STATE(37)] = 975,
  [SMALL_STATE(38)] = 993,
  [SMALL_STATE(39)] = 1013,
  [SMALL_STATE(40)] = 1035,
  [SMALL_STATE(41)] = 1059,
  [SMALL_STATE(42)] = 1085,
  [SMALL_STATE(43)] = 1113,
  [SMALL_STATE(44)] = 1129,
  [SMALL_STATE(45)] = 1145,
  [SMALL_STATE(46)] = 1168,
  [SMALL_STATE(47)] = 1191,
  [SMALL_STATE(48)] = 1214,
  [SMALL_STATE(49)] = 1237,
  [SMALL_STATE(50)] = 1260,
  [SMALL_STATE(51)] = 1283,
  [SMALL_STATE(52)] = 1306,
  [SMALL_STATE(53)] = 1329,
  [SMALL_STATE(54)] = 1352,
  [SMALL_STATE(55)] = 1375,
  [SMALL_STATE(56)] = 1398,
  [SMALL_STATE(57)] = 1421,
  [SMALL_STATE(58)] = 1444,
  [SMALL_STATE(59)] = 1467,
  [SMALL_STATE(60)] = 1490,
  [SMALL_STATE(61)] = 1513,
  [SMALL_STATE(62)] = 1536,
  [SMALL_STATE(63)] = 1559,
  [SMALL_STATE(64)] = 1582,
  [SMALL_STATE(65)] = 1605,
  [SMALL_STATE(66)] = 1628,
  [SMALL_STATE(67)] = 1651,
  [SMALL_STATE(68)] = 1674,
  [SMALL_STATE(69)] = 1697,
  [SMALL_STATE(70)] = 1720,
  [SMALL_STATE(71)] = 1743,
  [SMALL_STATE(72)] = 1766,
  [SMALL_STATE(73)] = 1784,
  [SMALL_STATE(74)] = 1802,
  [SMALL_STATE(75)] = 1820,
  [SMALL_STATE(76)] = 1838,
  [SMALL_STATE(77)] = 1856,
  [SMALL_STATE(78)] = 1874,
  [SMALL_STATE(79)] = 1885,
  [SMALL_STATE(80)] = 1896,
  [SMALL_STATE(81)] = 1907,
  [SMALL_STATE(82)] = 1918,
  [SMALL_STATE(83)] = 1929,
  [SMALL_STATE(84)] = 1940,
  [SMALL_STATE(85)] = 1951,
  [SMALL_STATE(86)] = 1962,
  [SMALL_STATE(87)] = 1973,
  [SMALL_STATE(88)] = 1984,
  [SMALL_STATE(89)] = 1995,
  [SMALL_STATE(90)] = 2006,
  [SMALL_STATE(91)] = 2017,
  [SMALL_STATE(92)] = 2028,
  [SMALL_STATE(93)] = 2039,
  [SMALL_STATE(94)] = 2050,
  [SMALL_STATE(95)] = 2061,
  [SMALL_STATE(96)] = 2072,
  [SMALL_STATE(97)] = 2083,
  [SMALL_STATE(98)] = 2094,
  [SMALL_STATE(99)] = 2105,
  [SMALL_STATE(100)] = 2116,
  [SMALL_STATE(101)] = 2132,
  [SMALL_STATE(102)] = 2148,
  [SMALL_STATE(103)] = 2157,
  [SMALL_STATE(104)] = 2168,
  [SMALL_STATE(105)] = 2179,
  [SMALL_STATE(106)] = 2186,
  [SMALL_STATE(107)] = 2193,
  [SMALL_STATE(108)] = 2200,
  [SMALL_STATE(109)] = 2209,
  [SMALL_STATE(110)] = 2216,
  [SMALL_STATE(111)] = 2226,
  [SMALL_STATE(112)] = 2236,
  [SMALL_STATE(113)] = 2246,
  [SMALL_STATE(114)] = 2256,
  [SMALL_STATE(115)] = 2263,
  [SMALL_STATE(116)] = 2270,
  [SMALL_STATE(117)] = 2277,
  [SMALL_STATE(118)] = 2282,
  [SMALL_STATE(119)] = 2287,
  [SMALL_STATE(120)] = 2294,
  [SMALL_STATE(121)] = 2301,
  [SMALL_STATE(122)] = 2308,
  [SMALL_STATE(123)] = 2315,
  [SMALL_STATE(124)] = 2322,
  [SMALL_STATE(125)] = 2326,
  [SMALL_STATE(126)] = 2330,
  [SMALL_STATE(127)] = 2334,
  [SMALL_STATE(128)] = 2338,
  [SMALL_STATE(129)] = 2342,
  [SMALL_STATE(130)] = 2346,
  [SMALL_STATE(131)] = 2350,
  [SMALL_STATE(132)] = 2354,
  [SMALL_STATE(133)] = 2358,
  [SMALL_STATE(134)] = 2362,
  [SMALL_STATE(135)] = 2366,
  [SMALL_STATE(136)] = 2370,
  [SMALL_STATE(137)] = 2374,
  [SMALL_STATE(138)] = 2378,
  [SMALL_STATE(139)] = 2382,
  [SMALL_STATE(140)] = 2386,
  [SMALL_STATE(141)] = 2390,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(127),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive_value, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_value, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 2),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 2),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_assignment, 3, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound_assignment, 3, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reassignment, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reassignment, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(127),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(140),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(140),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(125),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 4, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_definition, 5, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_definition, 5, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_definition, 4, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_definition, 4, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 5, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_loop, 3, 0, 1),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_loop, 3, 0, 1),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [258] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 4, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 3, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [268] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(119),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_def, 3, 0, 0),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_binding, 1, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_declaration, 2, 0, 0),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [307] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_type, 1, 0, 0),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_kon(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
